version: '3.8'

services:
  postgres:
    hostname: postgres
    image: postgres:latest
    env_file:
      - .dev.env
    volumes:
      - postgres_data:/var/services/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - .dev.env
    depends_on:
      - postgres
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/services/pgadmin

volumes:
  postgres_data:
  pgadmin_data: